config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'hikes#index'

  resources :hikes, only: [:index, :show, :new, :create]
  resources :users, only: [:index, :show]
  resources :user_hikes, only: [:index, :update, :destroy, :show, :edit] do
    resources :journal_entries, only: [:index, :new, :create]
  end
  resources :journal_entries, only: [:show, :update, :destroy]
  resources :wishlists, only: [:create, :update]
  resources :my_hikes, only: [:create]
  resources :gmaps, only: [:new]


  namespace :api do
    namespace :v1 do
      resources :hikes, only: [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user_hike
  has_one :user, through: :user_hikes
  has_one :hike, through: :user_hikes


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_hikes
  has_many :hikes, through: :user_hikes
  validates :username, presence: true, uniqueness: true
end

app/models/user_hike.rb
class UserHike < ApplicationRecord
  belongs_to :user
  belongs_to :hike
  has_many   :journal_entries
  validates :list, presence: true, inclusion: { in: ["wishlist", "my_hikes"] }
  validate :photo_size_validation
  mount_uploader :photo, PhotoUploader

  private

  def photo_size_validation
    errors[:photo] << "Photo must be less than 800KB" if photo.size > 0.8.megabytes
  end
end

app/controllers/api/v1/hikes_controller.rb
class Api::V1::HikesController < ApplicationController
  def index
    render json: Hike.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/gmaps_conotroller.rb
class GmapsController < ApplicationController
  def index
  end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  def index
    @hikes = Hike.all
    @ordered_hikes = Hike.all.order(country: :asc, name: :asc)
  end

  def show
    @hike = Hike.find(params[:id])
    @wishlist = UserHike.new
    @user = current_user
    @my_hike = UserHike.new
  end

  def new
    @new_hike = Hike.new
    @countries = Hike::COUNTRIES
    @difficulty_levels = ["EASY", "MODERATE", "HARD"]
  end

  def create
    @new_hike = Hike.new(hike_params)
    if @new_hike.save
      flash[:notice] = "Your trail has been added!"
      redirect_to hikes_path
    else
      flash[:alert] = "Your trail has not been added."
      @countries = Hike::COUNTRIES
      @difficulty_levels = ["EASY", "MODERATE", "HARD"]
      render :new
    end
  end

  private

  def hike_params
    params.require(:hike).permit(
      :name,
      :country,
      :state,
      :city,
      :difficulty,
      :elevation,
      :distance,
      :description
    )
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entries = @user_hike.journal_entries
    @journal_entry = JournalEntry.new
  end

  def show
    @journal_entry = JournalEntry.find(params[:id])
    @user_hike = @journal_entry.user_hike
  end

  def new
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entry = JournalEntry.new
  end

  def create
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entry = JournalEntry.new(journal_entry_params)
    @journal_entry.user_hike = @user_hike
    @journal_entries = @user_hike.journal_entries

    if @journal_entry.save
      flash[:notice] = "Your journal entry has been saved!"
      redirect_to user_hike_journal_entries_path
    else
      flash[:alert] = "Failed to save journal entry."
      render :new
    end
  end

  def update
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.update(journal_entry_params)
    if @journal_entry.save
      redirect_to journal_entry_path(@journal_entry), notice: "Your Trip Journal has been updated."
    else
      flash[:alert] = "#{@journal_entry.errors.messages}"
      redirect_to journal_entry_path(@journal_entry)
    end
  end

  def destroy
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.delete
    redirect_to journal_entries_path
  end

  private

  def journal_entry_params
    params.require(:journal_entry).permit(
      :date,
      :entry,
      :user_hike_id
    )
  end
end

app/controllers/my_hikes_controller.rb
class MyHikesController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def create
    @user = current_user
    @hike = Hike.find(params[:user_hike][:hike_id])
    if UserHike.exists?(user: @user, hike: @hike)
      @existing = UserHike.where(user: @user, hike: @hike)
      flash[:notice] = "#{@hike.name} is already on one of your lists."
      redirect_to user_hikes_path
    else
      @new_user_hike = UserHike.new(user: @user, hike: @hike, list: "my_hikes")
      if @new_user_hike.save
        flash[:notice] = "#{@hike.name} has been added to My Hikes."
        redirect_to user_hikes_path
      else
        flash[:alert] = "#{@hike.name} was not added to your list."
        render hike_path(@hike)
      end
    end
  end

  private

  def user_hike_params
    params.require(:user_hike).permit(:hike_id)
  end
end

app/controllers/user_hikes_controller.rb
class UserHikesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @user_hike = UserHike.find(params[:id])
    @journal_entries = JournalEntry.where(user_hike_id: @user_hike)
    @new_journal_entry = JournalEntry.new
  end

  def edit
    @user_hike = UserHike.find(params[:id])
  end

  def update
    @user_hike = UserHike.find(params[:id])
    @user_hike.update(user_hike_params)
    if @user_hike.save
      redirect_to user_hike_path(@user_hike), notice: "Your Trip Journal has been updated."
    else
      flash[:alert] = "#{@user_hike.errors.messages[:photo][0]}"
      redirect_to user_hike_path(@user_hike)
    end
  end

  def destroy
    @user_hike = UserHike.find(params[:id])
    @user_hike.delete
    redirect_to user_hikes_path
  end

  private

  def user_hike_params
    params.require(:user_hike).permit(
      :user_id,
      :hike_id,
      :list,
      :trip_details,
      :photo
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authorize_user, only: [:index]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


  # def authorize_user
  #   if !user_signed_in?
  #     raise ActionController::RoutingError.new("Not Found")
  #   end
  # end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = current_user
    @hike = Hike.find(params[:user_hike][:hike_id])
    if UserHike.exists?(user: @user, hike: @hike)
      @list =
      @existing = UserHike.where(user: @user, hike: @hike)
      flash[:notice] = "#{@hike.name} is already on one of your lists."
      redirect_to user_hikes_path
    else
      @new_user_hike = UserHike.new(user: @user, hike: @hike, list: "wishlist")
      if @new_user_hike.save
        flash[:notice] = "#{@hike.name} has been added to your Wishlist."
        redirect_to user_hikes_path
      else
        flash[:alert] = "#{@hike.name} was not added to your list."
        render hike_path(@hike)
      end
    end
  end

  def update
    @user_hike = UserHike.find(params[:id])
    @user_hike.update(list: "my_hikes")
    if @user_hike.save
      flash[:notice] = "#{@user_hike.hike.name} has been added to My Hikes."
      redirect_to user_hikes_path
    else
      flash[:alert] = "#{@user_hike.hike.name} could not be added to My Hikes."
    end
  end

  private

  def wishlist_params
    params.require(:user_hike).permit(:user_id, :hike_id, :list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/user_hikes/edit.html.erb
<div class="journal center-align"><br><h2>Trip Journal</h2><br></div>
<div class="container">
  <h2><%= @user_hike.hike.name %><h2>
  <div class="add-trip-details">
    <%= form_for @user_hike, url: user_hike_path(@user_hike), method: :patch do |f| %>
    <%= f.text_area :trip_details, class:"input-field trip-details", placeholder: "Add trip details" %>
    <div class="photo-field">
      <%= f.file_field :photo, class:"btn blue darken-2" %>
      <%= f.label :photo, "Add a photo (max 800kb)", class:"photo-field" %>
    </div>
    <%= f.submit "Add", class:"waves-effect waves-light btn blue darken-2" %>
    <% end %>
    <br><br>
  </div>
</div>

app/views/user_hikes/index.html.erb
<!-- # <%= image_tag('wakatipu.png', class: "panorama") %> -->
<div class="row">
  <div class="wishlist col s6 center-align">
    <h3 class="center-align">Wishlist</h3>
    <p class="center-align">Select to View Trail Details</p>
    <br>
      <% @wishlist = UserHike.where(user_id: current_user.id, list: "wishlist") %>
      <% if @wishlist.empty? %>
        <h5 class="">There are no hikes on your wishlist.</h5>
      <% else %>
        <% @wishlist.each do |item| %>
          <div class="row left-align">
            <div class="tooltip">
              <%= button_to " - ", user_hike_path(item.id), method: :delete, class:"remove btn grey col" %>
              <span class="tooltiptext left">&nbsp;&nbsp; Remove &nbsp;&nbsp;</span>
            </div>
            <div class="tooltip">
              <%= button_to " + ", wishlist_path(item.id), method: :patch, class:"add btn blue darken-2 col" %>
              <span class="tooltiptext">&nbsp;&nbsp; Add to My Hikes &nbsp;&nbsp;</span>
            </div>
            <div>
            <h5 class="">
              <%= link_to item.hike.name, hike_path(item.hike.id), class:""%>
            </h5>
          </div>
            <br>
          </div>
        <% end %>
      <% end %>

  </div>

  <div class="my_hikes col s6 center-align">
    <h3>My Hikes</h3>
    <p>Select to View/Add Trip Journal</p>
    <br>
    <% @my_hikes = UserHike.where(user_id: current_user.id, list: "my_hikes") %>
    <% if @my_hikes.empty? %>
      <h5>You haven't added any completed hikes yet.</h5>
    <% else %>
      <% @my_hikes.each do |item| %>
        <h5><%= link_to item.hike.name, user_hike_journal_entries_path(item.id) %></h5> <br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/user_hikes/show.html.erb
<div class="journal">
  <div class="journal center-align"><br>
    <h2>Trip Journal: <%= @user_hike.hike.name %></h2><br>
  </div>
  <div class="jrnl container">
    <div class="row">
      <div class="card">
      <div class="card-image">
      <%= image_tag @user_hike.photo, class:"photo" %>
    </div>
    <div class="card-content">
    <span class="card-title"><%= @user_hike.hike.name %></span>
    <div class="card-action">
    <%= link_to "Add/Edit Trip Details",   class:"btn blue darken-2 center-align" %>
    </div>
  </div>
  </div>

    </div>
  </div>
</div>