config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'hikes#index'

  resources :hikes, only: [:index, :show, :new, :create]
  resources :users, only: [:index, :show]
  resources :user_hikes, only: [:index, :update, :destroy, :show, :edit] do
    resources :journal_entries, only: [:index, :new, :create]
  end
  resources :journal_entries, only: [:show, :update, :destroy]
  resources :wishlists, only: [:create, :update]
  resources :my_hikes, only: [:create]
  resources :gmaps, only: [:new]


  namespace :api do
    namespace :v1 do
      resources :hikes, only: [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user_hike
  has_one :user, through: :user_hikes
  has_one :hike, through: :user_hikes


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_hikes
  has_many :hikes, through: :user_hikes
  validates :username, presence: true, uniqueness: true
end

app/models/user_hike.rb
class UserHike < ApplicationRecord
  belongs_to :user
  belongs_to :hike
  has_many   :journal_entries
  validates :list, presence: true, inclusion: { in: ["wishlist", "my_hikes"] }
  validate :photo_size_validation
  mount_uploader :photo, PhotoUploader

  private

  def photo_size_validation
    errors[:photo] << "Photo must be less than 800KB" if photo.size > 0.8.megabytes
  end
end

app/controllers/api/v1/hikes_controller.rb
class Api::V1::HikesController < ApplicationController
  def index
    render json: Hike.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/gmaps_conotroller.rb
class GmapsController < ApplicationController
  def index
  end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  def index
    @hikes = Hike.all
    @ordered_hikes = Hike.all.order(country: :asc, name: :asc)
  end

  def show
    @hike = Hike.find(params[:id])
    @wishlist = UserHike.new
    @user = current_user
    @my_hike = UserHike.new
  end

  def new
    @new_hike = Hike.new
    @countries = Hike::COUNTRIES
    @difficulty_levels = ["EASY", "MODERATE", "HARD"]
  end

  def create
    @new_hike = Hike.new(hike_params)
    if @new_hike.save
      flash[:notice] = "Your trail has been added!"
      redirect_to hikes_path
    else
      flash[:alert] = "Your trail has not been added."
      @countries = Hike::COUNTRIES
      @difficulty_levels = ["EASY", "MODERATE", "HARD"]
      render :new
    end
  end

  private

  def hike_params
    params.require(:hike).permit(
      :name,
      :country,
      :state,
      :city,
      :difficulty,
      :elevation,
      :distance,
      :description
    )
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entries = @user_hike.journal_entries
    @journal_entry = JournalEntry.new
  end

  def show
    @journal_entry = JournalEntry.find(params[:id])
    @user_hike = @journal_entry.user_hike
  end

  def new
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entry = JournalEntry.new
  end

  def create
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entry = JournalEntry.new(journal_entry_params)
    @journal_entry.user_hike = @user_hike
    @journal_entries = @user_hike.journal_entries

    if @journal_entry.save
      flash[:notice] = "Your journal entry has been saved!"
      redirect_to user_hike_journal_entries_path
    else
      flash[:alert] = "Failed to save journal entry."
      render :new
    end
  end

  def update
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.update(journal_entry_params)
    if @journal_entry.save
      redirect_to journal_entry_path(@journal_entry), notice: "Your Trip Journal has been updated."
    else
      flash[:alert] = "#{@journal_entry.errors.messages}"
      redirect_to journal_entry_path(@journal_entry)
    end
  end

  def destroy
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.delete
    redirect_to journal_entries_path
  end

  private

  def journal_entry_params
    params.require(:journal_entry).permit(
      :date,
      :entry,
      :user_hike_id
    )
  end
end

app/controllers/my_hikes_controller.rb
class MyHikesController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def create
    @user = current_user
    @hike = Hike.find(params[:user_hike][:hike_id])
    if UserHike.exists?(user: @user, hike: @hike)
      @existing = UserHike.where(user: @user, hike: @hike)
      flash[:notice] = "#{@hike.name} is already on one of your lists."
      redirect_to user_hikes_path
    else
      @new_user_hike = UserHike.new(user: @user, hike: @hike, list: "my_hikes")
      if @new_user_hike.save
        flash[:notice] = "#{@hike.name} has been added to My Hikes."
        redirect_to user_hikes_path
      else
        flash[:alert] = "#{@hike.name} was not added to your list."
        render hike_path(@hike)
      end
    end
  end

  private

  def user_hike_params
    params.require(:user_hike).permit(:hike_id)
  end
end

app/controllers/user_hikes_controller.rb
class UserHikesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @user_hike = UserHike.find(params[:id])
    @journal_entries = JournalEntry.where(user_hike_id: @user_hike)
    @new_journal_entry = JournalEntry.new
  end

  def edit
    @user_hike = UserHike.find(params[:id])
  end

  def update
    @user_hike = UserHike.find(params[:id])
    @user_hike.update(user_hike_params)
    if @user_hike.save
      redirect_to user_hike_path(@user_hike), notice: "Your Trip Journal has been updated."
    else
      flash[:alert] = "#{@user_hike.errors.messages[:photo][0]}"
      redirect_to user_hike_path(@user_hike)
    end
  end

  def destroy
    @user_hike = UserHike.find(params[:id])
    @user_hike.delete
    redirect_to user_hikes_path
  end

  private

  def user_hike_params
    params.require(:user_hike).permit(
      :user_id,
      :hike_id,
      :list,
      :trip_details,
      :photo
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authorize_user, only: [:index]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


  # def authorize_user
  #   if !user_signed_in?
  #     raise ActionController::RoutingError.new("Not Found")
  #   end
  # end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = current_user
    @hike = Hike.find(params[:user_hike][:hike_id])
    if UserHike.exists?(user: @user, hike: @hike)
      @list =
      @existing = UserHike.where(user: @user, hike: @hike)
      flash[:notice] = "#{@hike.name} is already on one of your lists."
      redirect_to user_hikes_path
    else
      @new_user_hike = UserHike.new(user: @user, hike: @hike, list: "wishlist")
      if @new_user_hike.save
        flash[:notice] = "#{@hike.name} has been added to your Wishlist."
        redirect_to user_hikes_path
      else
        flash[:alert] = "#{@hike.name} was not added to your list."
        render hike_path(@hike)
      end
    end
  end

  def update
    @user_hike = UserHike.find(params[:id])
    @user_hike.update(list: "my_hikes")
    if @user_hike.save
      flash[:notice] = "#{@user_hike.hike.name} has been added to My Hikes."
      redirect_to user_hikes_path
    else
      flash[:alert] = "#{@user_hike.hike.name} could not be added to My Hikes."
    end
  end

  private

  def wishlist_params
    params.require(:user_hike).permit(:user_id, :hike_id, :list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hikes/index.html.erb
<%= image_tag('wakatipu.png', class: "panorama") %>
<h4 class="right-align container"> <%= link_to "Add a Trail", new_hike_path  %></h4>
<br>

<input id="pac-input" class="controls" type="text" placeholder="Search (example: 'hiking trails near Denver')">
<div id="map"></div>
<div id="right-panel">
  <h2>Results</h2>
  <ul id="places"></ul>
  <button id="more">More results</button>
</div>

<div id="app" class=""></div>

app/views/hikes/new.html.erb
<div class="container">
  <h3 class="center">Add a Trail</h3>
    <div class="add-trail">
      <%= form_for @new_hike, method: :create, url: hikes_path, html: {class: "new_hike"} do |f| %>
      <div class="input-field">
        <%= f.text_field :name, placeholder: "Trail Name" %>
      </div>

      <div class="input-field">
        <%= f.select :country, @countries %>
      </div>

      <div class="input-field">
        <%= f.text_field :state, placeholder: "State (e.g. 'GA') or Province"%>
      </div>

      <div class="input-field">
        <%= f.text_field :city, placeholder: "City, Region, or Park Name" %>
      </div>

      <div class="input-field">
        <%= f.select :difficulty, @difficulty_levels %>

      </div>

      <div class="input-field">
        <%= f.number_field :distance, class: :text_field, step: :any, placeholder: "Distance (mi)" %>
      </div>

      <div class="input-field">
        <%= f.number_field :elevation, placeholder: "Elevation Gain (ft)" %>
      </div>

      <div class="input-field">
        <%= f.text_area :description, placeholder: "Description", class:"materialize-textarea" %>
      </div>

      <div class="actions">
        <%= f.submit "Add", class: "btn"%>
      </div>
    <% end %>
  </div>
  <br><br>
</div>

app/views/hikes/show.html.erb
<!-- <%= image_tag('wakatipu.png', class: "panorama") %> -->
<br><br>
<div class="z-depth-4 container">
  <br>
  <div class="hike-show container">
    <h2><%= @hike.name %></h2>
    <h4><%= "#{@hike.city}, #{@hike.state}, #{@hike.country}" %></h4>
    <h6> <%= "Difficulty: #{@hike.difficulty.upcase}" %> &nbsp; &nbsp; <%="Elevation Gain: #{@hike.elevation} ft" %> &nbsp; &nbsp;   <%= "Distance: #{@hike.distance} mi" %></h6>
    <h5><%= @hike.description %></h5>
  </div>
  <br>
  <div class="row center-align">
    <% if UserHike.find_by(user: current_user, hike: @hike, list: "wishlist") %>
      <div><h5 "center-align onlist">This trail is on your wishlist</h5></div>
      <br>
      <%= form_for @my_hike, url: my_hikes_path do |f| %>
      <%= f.hidden_field :hike_id, value: @hike.id %>
      <div class="center-align">
        <%= f.submit "Add to My Hikes", class:"waves-effect waves-light btn blue darken-2" %>
      </div>
      <% end %>
    <% elsif UserHike.find_by(user: current_user, hike: @hike, list: "my_hikes")%>
      <h5 class="center-align onlist">This trail is in your My Hikes list</h5>
    <% else %>
      <%= form_for @wishlist, url: wishlists_path do |f| %>
      <%= f.hidden_field :hike_id, value: @hike.id %>
      <div class="col s6 right-align">
        <%= f.submit "Add to Wishlist", class:"waves-effect waves-light btn blue darken-2" %>
      </div>
      <% end %>
      <%= form_for @my_hike, url: my_hikes_path do |f| %>
      <%= f.hidden_field :hike_id, value: @hike.id %>
      <div class="col s6 left-align">
        <%= f.submit "Add to My Hikes", class:"waves-effect waves-light btn blue darken-2" %>
      </div>
      <% end %>
    <% end %>
  </div>
  <br>
</div>
<br><br>