config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'hikes#index'

  resources :hikes, only: [:index, :show, :new, :create]
  resources :users, only: [:index, :show]
  resources :user_hikes, only: [:index, :update, :destroy, :show, :edit] do
    resources :journal_entries, only: [:index, :new, :create]
  end
  resources :journal_entries, only: [:show, :update, :destroy]
  resources :wishlists, only: [:create, :update]
  resources :my_hikes, only: [:create]
  resources :gmaps, only: [:new]


  namespace :api do
    namespace :v1 do
      resources :hikes, only: [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user_hike
  has_one :user, through: :user_hikes
  has_one :hike, through: :user_hikes


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_hikes
  has_many :hikes, through: :user_hikes
  validates :username, presence: true, uniqueness: true
end

app/models/user_hike.rb
class UserHike < ApplicationRecord
  belongs_to :user
  belongs_to :hike
  has_many   :journal_entries
  validates :list, presence: true, inclusion: { in: ["wishlist", "my_hikes"] }
  validate :photo_size_validation
  mount_uploader :photo, PhotoUploader

  private

  def photo_size_validation
    errors[:photo] << "Photo must be less than 800KB" if photo.size > 0.8.megabytes
  end
end

app/controllers/api/v1/hikes_controller.rb
class Api::V1::HikesController < ApplicationController
  def index
    render json: Hike.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/gmaps_conotroller.rb
class GmapsController < ApplicationController
  def index
  end
end

app/controllers/hikes_controller.rb
class HikesController < ApplicationController
  def index
    @hikes = Hike.all
    @ordered_hikes = Hike.all.order(country: :asc, name: :asc)
  end

  def show
    @hike = Hike.find(params[:id])
    @wishlist = UserHike.new
    @user = current_user
    @my_hike = UserHike.new
  end

  def new
    @new_hike = Hike.new
    @countries = Hike::COUNTRIES
    @difficulty_levels = ["EASY", "MODERATE", "HARD"]
  end

  def create
    @new_hike = Hike.new(hike_params)
    if @new_hike.save
      flash[:notice] = "Your trail has been added!"
      redirect_to hikes_path
    else
      flash[:alert] = "Your trail has not been added."
      @countries = Hike::COUNTRIES
      @difficulty_levels = ["EASY", "MODERATE", "HARD"]
      render :new
    end
  end

  private

  def hike_params
    params.require(:hike).permit(
      :name,
      :country,
      :state,
      :city,
      :difficulty,
      :elevation,
      :distance,
      :description
    )
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entries = @user_hike.journal_entries
    @journal_entry = JournalEntry.new
  end

  def show
    @journal_entry = JournalEntry.find(params[:id])
    @user_hike = @journal_entry.user_hike
  end

  def new
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entry = JournalEntry.new
  end

  def create
    @user_hike = UserHike.find(params[:user_hike_id])
    @journal_entry = JournalEntry.new(journal_entry_params)
    @journal_entry.user_hike = @user_hike
    @journal_entries = @user_hike.journal_entries

    if @journal_entry.save
      flash[:notice] = "Your journal entry has been saved!"
      redirect_to user_hike_journal_entries_path
    else
      flash[:alert] = "Failed to save journal entry."
      render :new
    end
  end

  def update
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.update(journal_entry_params)
    if @journal_entry.save
      redirect_to journal_entry_path(@journal_entry), notice: "Your Trip Journal has been updated."
    else
      flash[:alert] = "#{@journal_entry.errors.messages}"
      redirect_to journal_entry_path(@journal_entry)
    end
  end

  def destroy
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.delete
    redirect_to journal_entries_path
  end

  private

  def journal_entry_params
    params.require(:journal_entry).permit(
      :date,
      :entry,
      :user_hike_id
    )
  end
end

app/controllers/my_hikes_controller.rb
class MyHikesController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def create
    @user = current_user
    @hike = Hike.find(params[:user_hike][:hike_id])
    if UserHike.exists?(user: @user, hike: @hike)
      @existing = UserHike.where(user: @user, hike: @hike)
      flash[:notice] = "#{@hike.name} is already on one of your lists."
      redirect_to user_hikes_path
    else
      @new_user_hike = UserHike.new(user: @user, hike: @hike, list: "my_hikes")
      if @new_user_hike.save
        flash[:notice] = "#{@hike.name} has been added to My Hikes."
        redirect_to user_hikes_path
      else
        flash[:alert] = "#{@hike.name} was not added to your list."
        render hike_path(@hike)
      end
    end
  end

  private

  def user_hike_params
    params.require(:user_hike).permit(:hike_id)
  end
end

app/controllers/user_hikes_controller.rb
class UserHikesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @user_hike = UserHike.find(params[:id])
    @journal_entries = JournalEntry.where(user_hike_id: @user_hike)
    @new_journal_entry = JournalEntry.new
  end

  def edit
    @user_hike = UserHike.find(params[:id])
  end

  def update
    @user_hike = UserHike.find(params[:id])
    @user_hike.update(user_hike_params)
    if @user_hike.save
      redirect_to user_hike_path(@user_hike), notice: "Your Trip Journal has been updated."
    else
      flash[:alert] = "#{@user_hike.errors.messages[:photo][0]}"
      redirect_to user_hike_path(@user_hike)
    end
  end

  def destroy
    @user_hike = UserHike.find(params[:id])
    @user_hike.delete
    redirect_to user_hikes_path
  end

  private

  def user_hike_params
    params.require(:user_hike).permit(
      :user_id,
      :hike_id,
      :list,
      :trip_details,
      :photo
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authorize_user, only: [:index]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end


  # def authorize_user
  #   if !user_signed_in?
  #     raise ActionController::RoutingError.new("Not Found")
  #   end
  # end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = current_user
    @hike = Hike.find(params[:user_hike][:hike_id])
    if UserHike.exists?(user: @user, hike: @hike)
      @list =
      @existing = UserHike.where(user: @user, hike: @hike)
      flash[:notice] = "#{@hike.name} is already on one of your lists."
      redirect_to user_hikes_path
    else
      @new_user_hike = UserHike.new(user: @user, hike: @hike, list: "wishlist")
      if @new_user_hike.save
        flash[:notice] = "#{@hike.name} has been added to your Wishlist."
        redirect_to user_hikes_path
      else
        flash[:alert] = "#{@hike.name} was not added to your list."
        render hike_path(@hike)
      end
    end
  end

  def update
    @user_hike = UserHike.find(params[:id])
    @user_hike.update(list: "my_hikes")
    if @user_hike.save
      flash[:notice] = "#{@user_hike.hike.name} has been added to My Hikes."
      redirect_to user_hikes_path
    else
      flash[:alert] = "#{@user_hike.hike.name} could not be added to My Hikes."
    end
  end

  private

  def wishlist_params
    params.require(:user_hike).permit(:user_id, :hike_id, :list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<div class="row navbar">
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo trailhead blue-text text-darken-3">Trailhead</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down blue-text">
        <% if current_user %>
          <li><%= link_to "My Lists", user_hikes_path, class:"blue-text text-darken-3"%></li>
          &nbsp; &nbsp;
          <li class="blue-text"><%= link_to current_user.username, user_path(current_user.id), class:"blue-text text-darken-3"%></li>
          &nbsp; &nbsp;
          <li class="blue-text"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"blue-text text-darken-3" %></li>
        <% else  %>
          <li class="blue-text"><%= link_to 'Create Account', new_user_registration_path, class:"blue-text text-darken-3" %></li>
          &nbsp; &nbsp;
          <li class="blue-text"><%= link_to "Sign In", new_user_session_path, class:"blue-text text-darken-3" %></li>
        <% end  %>
      </ul>
    </div>
  </nav>
</div>

<!-- <div><%= image_tag('wakatipu.png', class: "panorama")%></div> -->
<div class="row options">
  <div class="col s12">
    <ul class="">
      <li class="col s4 center"><%= link_to 'BROWSE', hikes_path %></li>
      <li class="col s4 center">
        <a class="tooltip search-link">
          <span class="tooltiptext search-link">Coming Soon</span>
          SEARCH
        </a>
      </li>
      <li class="col s4 center"><%= link_to "ADD", new_hike_path  %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trailhead</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1 user-scalable=no">
    <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://unpkg.com/react-table@latest/react-table.css">
    <script src="https://use.fontawesome.com/73f3ebf533.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <% if flash[:notice] %>
      <script type="text/javascript">
      Materialize.toast('<%= notice %>', 5000)
      </script>
    <% elsif flash[:error] %>
      <script type="text/javascript">
      Materialize.toast('<%= flash[:error] %>', 5000)
      </script>
    <% elsif flash[:alert] %>
      <script type="text/javascript">
      Materialize.toast('<%= alert %>', 5000)
      </script>
    <% end %>

    <%= yield %>

  <script  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&libraries=places&callback=initAutocomplete" async defer>
  </script>
  </body>
</html>